// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// /// // ...
//  await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoTAmwb7KJZo0Ivd-hAcQmtRSOQodRvFI',
    appId: '1:716648266797:web:5bff4016d312fd9e548ca4',
    messagingSenderId: '716648266797',
    projectId: 'kallioapp',
    authDomain: 'kallioapp.firebaseapp.com',
    storageBucket: 'kallioapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSzYi2Asm6rRRga4mpHdoe9S5pThnB8Q0',
    appId: '1:716648266797:android:4eb7d82b6f942aa6548ca4',
    messagingSenderId: '716648266797',
    projectId: 'kallioapp',
    storageBucket: 'kallioapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFwjWCisSkyd25caLZE-UlRDkGm_EyFZk',
    appId: '1:716648266797:ios:d5894b15f8058d97548ca4',
    messagingSenderId: '716648266797',
    projectId: 'kallioapp',
    storageBucket: 'kallioapp.firebasestorage.app',
    iosBundleId: 'com.example.fcmTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFwjWCisSkyd25caLZE-UlRDkGm_EyFZk',
    appId: '1:716648266797:ios:d5894b15f8058d97548ca4',
    messagingSenderId: '716648266797',
    projectId: 'kallioapp',
    storageBucket: 'kallioapp.firebasestorage.app',
    iosBundleId: 'com.example.fcmTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQwrUi8witOFfDJytsuS8tUoWZSORgCjA',
    appId: '1:716648266797:web:87ba463f8b53feaf548ca4',
    messagingSenderId: '716648266797',
    projectId: 'kallioapp',
    authDomain: 'kallioapp.firebaseapp.com',
    storageBucket: 'kallioapp.firebasestorage.app',
  );

}
